spring:
  application:
    name: dailyLog
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

#    url: jdbc:mariadb://localhost:3307/mariadb
#    url: jdbc:mariadb://localhost:3333/mariadb
    url: jdbc:mariadb://localhost:3306/newjeans?serverTimezone=Asia/Seoul

    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true


  jwt:
    secret: abcdefghijklmnopqrstuvwxyz0dscvdsvcsdvqfeewffsdfsdfsafsafsf

my:
  value: "welcome to my value"

itemImgLocation: "C:/files"
uploadPath: "file:///C:/files/"



