server:
  port: 20010

spring:
  application:
    name: dailyLog
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

    url: jdbc:mariadb://localhost:3306/mariadb
#    url: jdbc:mariadb://localhost:3333/mariadb
#    url: jdbc:mariadb://localhost:3306/newjeans?serverTimezone=Asia/Seoul

    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true


  jwt:
    secret: abcdefghijklmnopqrstuvwxyz0dscvdsvcsdvqfeewffsdfsdfsafsafsf

my:
  value: "welcome to my value"

# 로컬 이미지 저장 루트
ImgLocation: "D:/images"
ProfileImgLocation: "D:/profileImages"
uploadPath: "file:///D:/images/"
profileUploadPath: "file:///D:/profileImages/"

## 서버 이미지 저장 루트
#ImgLocation: "/app/images"
#ProfileImgLocation: "/app/profileImages"
#uploadPath: "file:///D:/images/"
#profileUploadPath: "file:///D:/profileImages/"


